/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GradleSpringCore;

import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

public class Library {

	  public boolean someLibraryMethod() {

	    return true;

	  }

	  public static void main(String[] args) {

	 ApplicationContext ctx=new ClassPathXmlApplicationContext("bean.xml");

	 Employee e=	ctx.getBean(Employee.class);

	 System.out.println(e);

	 }

	}



